services:
  dashboard:
    build: .
    ports:
      - "8501:8501"
    environment:
      # Set your OpenAI API key here or in .env file
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      # Mount data directory to allow for data updates without rebuilding
      - ./data:/app/data:ro
      # Mount analysis directory to persist analysis results (with proper permissions)
      - ./analysis:/app/analysis
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
